service: pg-data-crawler

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: data-crawler
  apiName: pgdata
  memorySize: 512
  timeout: 15
  logRetentionInDays: 14
  deploymentBucket: 
    name: rijwan-pg-data
  dynamodb:
    stages:
      - dev
    start:
      host: localhost
      port: 8000
      migrate: true
      seed: true
      sharedDb: true
      dbPath: ${env:HOME}/dynamodb-local
    seed:
      domain:
        sources:
          - table: location
            sources: [./local-data/location.json]

resources:
  Resources:
    LocationTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: location
        AttributeDefinitions:
          - AttributeName: locationId
            AttributeType: S
        KeySchema:
          - AttributeName: locationId
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
  
functions:
  dataCrawler:
    handler: app.handler
    events:
      - http:
          path: data
          method: get
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
      - http:
          path: save
          method: get
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"